export const BRAND = {
  bg: '#FFF8FC',
  surface: '#FFFFFF',
  border: '#F2D7E7',
  text: '#191919',
  muted: '#7E6E78',
  blue: '#2F80ED',
  cyan: '#42D7D0',
  pink: '#EC4AA8',
  magenta: '#C93ECF',
  purple: '#7B3FE4',
};

export const HOBBY_OPTIONS = [
  'Music',
  'Art',
  'Gaming',
  'Fitness',
  'Travel',
  'Nature',
  'Books',
  'Meditation',
  'Astrology',
  'Tarot',
  'Festivals',
  'Cooking',
  'Yoga',
  'Hiking',
  'Movies',
  'Photography',
  'Dancing',
  'Fashion',
  'Poetry',
  'Podcasts',
  'B.D.S.M',
];

export const SPIRITUAL_PATH_OPTIONS = [
  'Spiritual',
  'Agnostic',
  'Atheist',
  'Christian',
  'Catholic',
  'Muslim',
  'Jewish',
  'Buddhist',
  'Hindu',
  'Pagan',
  'Wiccan',
  'Astrology',
  'Tarot',
  'Energy work',
  'Meditation',
  'Manifestation',
  'Mystic',
  'Curious',
];

export const RELATIONSHIP_STYLE_OPTIONS = [
  'Monogamous',
  'Monogamish',
  'Exploring',
  'Open relationship',
  'Polyamorous',
  'Solo poly',
  'Kitchen table poly',
  'Parallel poly',
  'Hierarchical poly',
  'Non-hierarchical poly',
  'Relationship anarchy',
  'V dynamic',
  'Hinge',
  'Triad',
  'Throuple',
  'Quad',
  'Polycule',
  'Closed polycule',
  'Open polycule',
  'Friends with benefits',
  'Still figuring it out',
];